// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

const EVENTS_SERVICE_URL = import.meta.env.VITE_EVENTS_SERVICE_URL as string;
const API_KEY = import.meta.env.VITE_API_KEY as string;

const prepareHeaders = (headers: Headers) => {
    headers.set('x-api-key', API_KEY);
    return headers;
};

export interface CalendarEvent {
    id: string;
    eventDate: string;
    eventDescription: string;
}

interface EventsApiResponse {
    data: CalendarEvent[] | null;
    errorMessage: string | null;
}

// Define a service using a base URL and expected endpoints
export const eventsApiSlice = createApi({
    baseQuery: fetchBaseQuery({
        baseUrl: EVENTS_SERVICE_URL,
        prepareHeaders,
    }),

    reducerPath: 'eventsApi',
    // Tag types are used for caching and invalidation.
    tagTypes: ['Events'],
    endpoints: (build) => ({
        // Supply generics for the return type (in this case `EventsApiResponse`)
        // and the expected query argument. If there is no argument, use `void`
        // for the argument type instead.
        getEvents: build.query<EventsApiResponse, void>({
            query: () => '',
            // `providesTags` determines which 'tag' is attached to the
            // cached data returned by the query.
            providesTags: ['Events'],
        }),
        postEvent: build.mutation<CalendarEvent, Partial<CalendarEvent>>({
            query: (newEvent) => ({
                url: '',
                method: 'POST',
                body: newEvent,
            }),
            invalidatesTags: ['Events'], // Invalidate the 'Events' cache to refetch data
        }),
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `eventsApiSlice.endpoints.getEvents.useQuery`
export const { useGetEventsQuery, usePostEventMutation } = eventsApiSlice;

export const selectEventsByDate = (
    events: CalendarEvent[] | null,
    selectedDate: string
) => {
    if (!events) return [];
    return events.filter(
        (event: CalendarEvent) =>
            event.eventDate.substring(0, 10) === selectedDate?.substring(0, 10)
    );
};
